tools = {
      '1':'git clone https://github.com/Gameye98/Lazymux.git',
      '2':'git clone https://github.com/p4kl0nc4t/Spammer-Grab.git',
      '3':'git clone https://github.com/inconshreveable/ngrok.git',
      '4':'git clone https://github.com/cyweb/hammer.git',
      '5':'git clone https://github.com/grafov/hulk.git',
      '6':'git clone https://github.com/derv82/wifite.git',
      '7':'git clone https://github.com/sabri-zaki/EasY_HaCk.git',
      '8':'git clone https://github.com/israelbuitron/wifi-scanner.git',
      '9':'git clone https://github.com/sqlmapproject/sqlmap.git',
      '10':'git clone https://github.com/rajkumardusad/Tool-X.git',
      '11':'git clone https://github.com/emre/fb.py.git',
      '12':'git clone https://github.com/Vairous7x/V7x-Fishing2.git',
      '13':'git clone https://github.com/Vairous7x/V7x-Tool.git',
      '14':'git clone https://github.com/No-Name-404/N404-Tool.git',
      '15':'git clone https://github.com/beefproject/beef.git',
      '16':'git clone https://github.com/nmilosev/termux-fedora.git',
    }
